name: Deploy MultiDocker
on:
  push:
    branches:
      - master # check your repo, your default branch might be master! 
 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - run: docker build -t bascualarcon/react-test -f ./client/Dockerfile.dev ./client
      - run: docker run -e CI=true bascualarcon/react-test npm test
 
      - run: docker build -t bascualarcon/multi-client-11-11 ./client
      - run: docker build -t bascualarcon/multi-nginx-11-11 ./nginx
      - run: docker build -t bascualarcon/multi-server-11-11 ./server
      - run: docker build -t bascualarcon/multi-worker-11-11 ./worker
 
      - run: docker push bascualarcon/multi-client-11-11
      - run: docker push bascualarcon/multi-nginx-11-11
      - run: docker push bascualarcon/multi-server-11-11
      - run: docker push bascualarcon/multi-worker-11-11
 
      # deploy to Elastic Beanstalk AWS

      # - name: Generate deployment package
      #   run: zip -r deploy.zip . -x '*.git*'
 
      # - name: Deploy to EB
      #   uses: einaregilsson/beanstalk-deploy@v18
      #   with:
      #     aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
      #     aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
      #     application_name: multi-gh
      #     environment_name: Multigh-env
      #     existing_bucket_name: elasticbeanstalk-us-east-1-923445559289
      #     region: us-east-1
      #     version_label: ${{ github.sha }}
      #     deployment_package: deploy.zip